"""
SQLAlchemy ORM models for the patches and validation_results tables.

See docs/db-schema.md section 5 for the full DDL.
"""

import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Patch(Base):
    """
    A code patch generated by the Transformer agent for an automated plan task.

    Stores the full diff and original/patched file content. Patches progress
    through status: pending -> applied | reverted | failed.
    """

    __tablename__ = "patches"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    task_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("plan_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Relative path of the file being patched within the repository.
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    # PatchType: 'modify' | 'create' | 'delete' | 'rename'
    patch_type: Mapped[str] = mapped_column(Text, nullable=False)
    # Language of the patched file.
    language: Mapped[str] = mapped_column(Text, nullable=False)
    # PatchStatus: 'pending' | 'applied' | 'reverted' | 'failed'
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")

    # File content — stored as TEXT; large patches may span multiple KB.
    original_content: Mapped[str] = mapped_column(Text, nullable=False)
    patched_content: Mapped[str] = mapped_column(Text, nullable=False)
    # Unified diff format output from Python difflib.unified_diff.
    diff: Mapped[str] = mapped_column(Text, nullable=False)

    # LLM metadata.
    tokens_used: Mapped[int | None] = mapped_column(Integer)
    model_used: Mapped[str | None] = mapped_column(Text)

    # Application tracking — updated when users confirm applying/reverting.
    applied_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    applied_by: Mapped[str | None] = mapped_column(Text)
    reverted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    reverted_reason: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )

    # Relationships.
    job: Mapped["Job"] = relationship("Job", back_populates="patches")  # noqa: F821
    task: Mapped["PlanTask"] = relationship("PlanTask", back_populates="patches")  # noqa: F821
    validation_results: Mapped[list["ValidationResult"]] = relationship(
        "ValidationResult",
        back_populates="patch",
        cascade="all, delete-orphan",
        lazy="select",
    )


class ValidationResult(Base):
    """
    Result of a sandbox validation run for a single code patch.

    Each run executes multiple checks (syntax, lint, test, semantic, security).
    The ``checks`` JSONB column stores the array of per-check results.
    """

    __tablename__ = "validation_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    patch_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("patches.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    passed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    # Aggregate score 0.0–1.0.
    overall_score: Mapped[float] = mapped_column(Float, nullable=False)
    # Array of ValidationCheck dicts:
    # { check_name, check_type, passed, output, duration_ms }
    checks: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )

    # Relationships.
    patch: Mapped["Patch"] = relationship("Patch", back_populates="validation_results")
