"""
SQLAlchemy ORM models for the plans and plan_tasks tables.

See docs/db-schema.md section 5 for the full DDL.
"""

import uuid
from datetime import UTC, datetime

from sqlalchemy import ARRAY, Boolean, DateTime, Float, ForeignKey, Integer, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Plan(Base):
    """
    A refactor plan generated by the Planner agent for a job.

    Plans are versioned — if a user requests regeneration a new plan record is
    created with an incremented version number. The most recent version is used
    by default in API responses.
    """

    __tablename__ = "plans"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Version number — increments with each regeneration (starts at 1).
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    # LLM-estimated total effort in hours for all tasks in this plan.
    estimated_effort_hours: Mapped[float | None] = mapped_column(Float)
    # Overall risk level: 'critical' | 'high' | 'medium' | 'low'
    risk_level: Mapped[str | None] = mapped_column(Text)
    # Ordered array of plan_tasks.id values in recommended execution order.
    priority_order: Mapped[list] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    # LLM model used to generate this plan.
    llm_model: Mapped[str | None] = mapped_column(Text)
    # Total tokens consumed during plan generation.
    tokens_used: Mapped[int | None] = mapped_column(Integer)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )

    # Relationships.
    job: Mapped["Job"] = relationship("Job", back_populates="plans")  # noqa: F821
    tasks: Mapped[list["PlanTask"]] = relationship(
        "PlanTask",
        back_populates="plan",
        cascade="all, delete-orphan",
        order_by="PlanTask.created_at",
        lazy="select",
    )


class PlanTask(Base):
    """
    An individual refactoring task within a plan.

    Tasks are the atomic unit of the refactor plan. Each task targets one or
    more smells and specifies the refactor pattern to apply. Tasks with
    ``automated=True`` can have patches generated automatically by the
    Transformer agent.
    """

    __tablename__ = "plan_tasks"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # References to smell IDs this task addresses.
    smell_ids: Mapped[list] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    # Source files that will be modified by this task.
    affected_files: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    # RefactorPattern enum value (e.g., "extract_class", "extract_method").
    refactor_pattern: Mapped[str] = mapped_column(Text, nullable=False)
    # IDs of other PlanTask records that must be applied before this one.
    dependencies: Mapped[list] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    estimated_hours: Mapped[float | None] = mapped_column(Float)
    # True if the Transformer agent can generate a patch automatically.
    automated: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    # Task status: 'pending' | 'approved' | 'rejected' | 'applied'
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    # Optional user-defined priority override (lower = higher priority).
    priority_override: Mapped[int | None] = mapped_column(Integer)
    # Optional reviewer notes.
    notes: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )

    # Relationships.
    plan: Mapped["Plan"] = relationship("Plan", back_populates="tasks")
    patches: Mapped[list["Patch"]] = relationship(  # noqa: F821
        "Patch",
        back_populates="task",
        cascade="all, delete-orphan",
        lazy="select",
    )
